// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601180656_ExpandMenu")]
    partial class ExpandMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Pizzas"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Sides"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("web.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("web.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SizeName")
                        .HasColumnType("text");

                    b.Property<string>("ToppingsSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("web.Models.PizzaSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceModifier")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PizzaSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Small (10\")",
                            PriceModifier = 0.00m
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Medium (12\")",
                            PriceModifier = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Large (14\")",
                            PriceModifier = 6.00m
                        });
                });

            modelBuilder.Entity("web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 11.99m,
                            CategoryId = 1,
                            Description = "Classic tomato sauce, fresh mozzarella and basil.",
                            ImageUrl = "/images/menu/margherita.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Margherita"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 13.99m,
                            CategoryId = 1,
                            Description = "Tomato sauce, mozzarella and a generous layer of pepperoni.",
                            ImageUrl = "/images/menu/pepperoni.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Pepperoni"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 13.49m,
                            CategoryId = 1,
                            Description = "Ham, pineapple and mozzarella on a tomato base.",
                            ImageUrl = "/images/menu/hawaiian.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Hawaiian"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 15.99m,
                            CategoryId = 1,
                            Description = "Pepperoni, bacon, ham, ground beef and mozzarella.",
                            ImageUrl = "/images/menu/meat-lovers.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Meat Lovers"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 13.99m,
                            CategoryId = 1,
                            Description = "Mushrooms, peppers, onions, olives and tomatoes.",
                            ImageUrl = "/images/menu/veggie-supreme.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Veggie Supreme"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 14.99m,
                            CategoryId = 1,
                            Description = "Grilled chicken, red onion and BBQ sauce.",
                            ImageUrl = "/images/menu/bbq-chicken.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "BBQ Chicken"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 13.99m,
                            CategoryId = 1,
                            Description = "Mozzarella, cheddar, parmesan and blue cheese.",
                            ImageUrl = "/images/menu/four-cheese.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Four Cheese"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 14.49m,
                            CategoryId = 1,
                            Description = "Spicy salami, chilli flakes and jalapeños.",
                            ImageUrl = "/images/menu/diavola.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Spicy Diavola"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 5.99m,
                            CategoryId = 2,
                            Description = "Oven-baked bread with garlic butter and herbs.",
                            ImageUrl = "/images/menu/garlic-bread.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Garlic Bread"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 9.99m,
                            CategoryId = 2,
                            Description = "Crispy wings with your choice of dip.",
                            ImageUrl = "/images/menu/chicken-wings.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Chicken Wings (8 pc)"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 7.49m,
                            CategoryId = 2,
                            Description = "Romaine, parmesan, croutons and Caesar dressing.",
                            ImageUrl = "/images/menu/caesar-salad.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Caesar Salad"
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 2.49m,
                            CategoryId = 3,
                            Description = "Chilled bottle of Coca-Cola.",
                            ImageUrl = "/images/menu/coca-cola.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Coca-Cola (500 ml)"
                        },
                        new
                        {
                            Id = 13,
                            BasePrice = 1.99m,
                            CategoryId = 3,
                            Description = "Refreshing sparkling mineral water.",
                            ImageUrl = "/images/menu/sparkling-water.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Sparkling Water"
                        },
                        new
                        {
                            Id = 14,
                            BasePrice = 3.49m,
                            CategoryId = 3,
                            Description = "Freshly squeezed orange juice.",
                            ImageUrl = "/images/menu/orange-juice.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Orange Juice"
                        },
                        new
                        {
                            Id = 15,
                            BasePrice = 14.49m,
                            CategoryId = 1,
                            Description = "Ham, mushrooms, artichokes, olives and mozzarella.",
                            ImageUrl = "/images/menu/capricciosa.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Capricciosa"
                        },
                        new
                        {
                            Id = 16,
                            BasePrice = 10.99m,
                            CategoryId = 1,
                            Description = "Tomato, garlic, oregano and olive oil — no cheese.",
                            ImageUrl = "/images/menu/marinara.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Marinara"
                        },
                        new
                        {
                            Id = 17,
                            BasePrice = 13.99m,
                            CategoryId = 1,
                            Description = "Folded pizza stuffed with ham, mushrooms and mozzarella.",
                            ImageUrl = "/images/menu/calzone.jpg",
                            IsAvailable = true,
                            IsCustomizable = true,
                            Name = "Calzone"
                        },
                        new
                        {
                            Id = 18,
                            BasePrice = 6.99m,
                            CategoryId = 2,
                            Description = "Breaded mozzarella with a marinara dip.",
                            ImageUrl = "/images/menu/mozzarella-sticks.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Mozzarella Sticks"
                        },
                        new
                        {
                            Id = 19,
                            BasePrice = 5.49m,
                            CategoryId = 2,
                            Description = "Crispy battered onion rings.",
                            ImageUrl = "/images/menu/onion-rings.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Onion Rings"
                        },
                        new
                        {
                            Id = 20,
                            BasePrice = 2.49m,
                            CategoryId = 3,
                            Description = "Chilled lemon-lime soda.",
                            ImageUrl = "/images/menu/sprite.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Sprite (500 ml)"
                        },
                        new
                        {
                            Id = 21,
                            BasePrice = 2.99m,
                            CategoryId = 3,
                            Description = "Freshly brewed iced tea with lemon.",
                            ImageUrl = "/images/menu/iced-tea.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Iced Tea"
                        },
                        new
                        {
                            Id = 22,
                            BasePrice = 6.49m,
                            CategoryId = 4,
                            Description = "Classic Italian coffee and mascarpone dessert.",
                            ImageUrl = "/images/menu/tiramisu.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Tiramisu"
                        },
                        new
                        {
                            Id = 23,
                            BasePrice = 5.49m,
                            CategoryId = 4,
                            Description = "Warm fudgy chocolate brownie.",
                            ImageUrl = "/images/menu/chocolate-brownie.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Chocolate Brownie"
                        },
                        new
                        {
                            Id = 24,
                            BasePrice = 6.99m,
                            CategoryId = 4,
                            Description = "New York style cheesecake with berries.",
                            ImageUrl = "/images/menu/cheesecake.jpg",
                            IsAvailable = true,
                            IsCustomizable = false,
                            Name = "Cheesecake"
                        });
                });

            modelBuilder.Entity("web.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Extra cheese",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Pepperoni",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Mushrooms",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Bacon",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Onions",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Bell peppers",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Olives",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Jalapeños",
                            Price = 0.75m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("web.Models.OrderItem", b =>
                {
                    b.HasOne("web.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("web.Models.Product", b =>
                {
                    b.HasOne("web.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("web.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
